    namespace Serialization {
        class TypeRT {
            +GetFloat()
            +GetDouble()
            +GetBool()
            +GetString()
            +GetChar()
            +GetInt()
            +GetUInt()
            +GetObjID()
            +GetULong()
            +GetRawData()
            +SetFloat()
            +SetDouble()
            +SetBool()
            +SetString()
            +SetChar()
            +SetInt()
            +SetUInt()
            +SetObjID()
            +SetULong()
            +SetRawData()
            +operator=()
            +operator==()
            +operator!=()
            +operator<<()
            +SetTypeName()
            +GetTypeName()
            +SetVariableName()
            +GetVariableName()
            +InsertMemb er()
            +IsBase()
            +Member()
            +Members()
            +Array()
            +Stream()
            +To_CSV_Format()
        }
    }
