    namespace External {
        interface InputSourceInterface {
            +SetKeyboardCallback()
            +SetMousePosCallback()
            +SetMouseButtonCallback()
            +SetGamepadButtonCallback()
            +SetGamepadAxisCallbackFunction()
            +SetConnectionStateCallbackFunction()
            +MapLetterToScancode()
            +MapMouseButtonToScancode()
        }
    }
