    namespace GameObjectFiltering {
        class ComponentTypeSet {
            +SetType()
            +Reset()
            +operator==()
            +operator<()
            +IsEmpty()
        }
    }
