    namespace GameObjectFiltering {
        class GameObjectFilter {
            +MoveGameObject()
            +SetBuilder()
        }
        GameObjectFilter -up-|> GameObjectCollector
        GameObjectFilter -up-|> GameObjectGatherer
    }
