    namespace InputSystem {
        class InputSystem {
            +MapLetterToScancode()
            +AddInputSource()
            {static} +GetName()
            +Name()
            {static} +GetAllKeys()
            #OnInitialize()
            #OnStartFrame()
            #OnShutdown()
        }
        InputSystem --|> SystemManagement::SystemBase
    }
