    namespace Serialization {
        class PersistenceRequest<T> {
            +Execute()
            +WriteDataToFile()
            +ReadDataFromFile()
            +GetData()
            +GetFolderName()
            +GetFileName()
            +GetRelativePath()
        }
    }