    namespace Serialization {
        class PersistenceSystem {
            {static} +GetName()
            +Name()
            +OnHandleMessage()
            +OnUpdate()
            +ObjectToStream()
            +GetDataLocation()
            +WriteToFile()
            +ReadFromFile()
        }
        PersistenceSystem --|> SystemManagement::SystemBase
    }
