    namespace SceneManagement {
        class ComponentType {
            {static} +ForConcrete()
            {static} +ForAbstract()
            {static} +ForInherited()
            +Name()
            +operator==()
            +operator<=()
            +HasParent()
            +GetParentType()
        }
    }
