    namespace SceneManagement {
        class Component {
            {abstract} +Type()
            {abstract} +ToTypeRT()
            {abstract} +UpdateFromTypeRT()
            +GetGameObject()
        }
    }
