    namespace Graphics::Camera {
        class CameraBase {
            {abstract} +process()
            {abstract} +processNoTransform()
            {abstract} +calcViewMatrix()
            {abstract} +calcProjMatrix()
            {abstract} +calcViewProjMatrix()
            {abstract} +calcCamPosition()
            +GetViewProjectMatrix()
            +GetViewMatrix()
            +GetProjectMatrix()
            +SetCameraUniforms()
            +SetProjectMatrix()
            +SetViewMatrix()
            +SetViewProjectionMatrix()
            +SetFieldOfViewDegree()
            +GetFieldOfViewDegree()
            +SetDimension()
            +GetWidth()
            +SetWidth()
            +GetHeight()
            +SetHeight()
            +GetNearPlaneDistance()
            +SetNearPlaneDistance()
            +GetFarPlaneDistance()
            +SetFarPlaneDistance()
            +PrintData()
            +PrintMatrices()
            +GetActive()
            +SetActive()
        }
    }
