    namespace Graphics::Rendering {
        class GraphicsSystem {
            {static} +GetName()
            +Name()
            +OnInitialize()
            +OnStartFrame()
            +OnUpdate()
            +OnEndFrame()
            +OnShutdown()
            +GetMeshManager()
            +GetShaderManager()
            +GetVertexArrayManager()
            +GetMaterialManager()
            +GetTextureManager()
            +GetFramebufferManager()
        }
        GraphicsSystem --|> SystemManagement::SystemBase
    }
