    namespace Graphics::Rendering {
        class MeshManager {
            +CreateMesh()
            +AddMesh()
            +BuildFullScreenQuad()
            +BuildSphere()
            +GetMesh()
        }
    }
