    namespace Graphics::Particles {
        class ParticleSystem {
            {static} +GetName()
            +Name()
            +OnInitialize()
            +OnUpdate()
        }
        ParticleSystem --|> SystemManagement::SystemBase
    }
