    namespace Graphics::Rendering {
        class TextureManager {
            +GetSimpleTexture()
            +GetCubeTexture()
            +UnbindAll()
            +CreateSimpleTexture()
            +CreateCubeTexture()
        }
    }
