    namespace Graphics::Rendering {
        class VertexArrayObject {
            +operator=()
            +GetIndexBufferObject()
            +GetVertexBufferObject()
            +Build()
            +Bind()
            +Render()
            +Unbind()
        }
    }
